worker_processes 1;

events {
    worker_connections 1024;
}

http {
    ssl_session_cache    shared:SSL:10m;
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 443 ssl;
        ssl_certificate    /ssl/__uteq_edu_ec2026Enero_cert_out.pem;
        ssl_certificate_key    /ssl/__uteq_edu_ec.key;

        server_name localhost aplicaciones.uteq.edu.ec;
        access_log /etc/nginx/logs/access.log;
        error_log /etc/nginx/logs/error.log;

        root /usr/share/nginx/html;
        index index.html;

        # Cache static assets
        location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2)$ {
            expires 30d;
            add_header Cache-Control "public, immutable";
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}